repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10000']

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy check
        entry: mypy ./
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest check . directory
        entry: ruff check . --fix
        language: system
        pass_filenames: false
